ignore:
  - "tests"
  - "**/*__init__.py"
  - "main.py"
  - "setup.py"
  - "nexus_constructor/kafka/kafka*"

comment:
  layout: "header, diff, tree, changes, sunburst"
  require_changes: false
  
coverage:
  status:
    patch: off
    project: off
