import json

import pytest


@pytest.fixture(scope="function")
def off_shape_json() -> dict:
    """
    Mesh for a simple unit cube, centred at 0, 0, 0
    """
    off_shape = """
    {
      "type":"group",
      "name":"shape",
      "children":[
        {
          "type":"dataset",
          "name":"faces",
          "dataset":{
            "type":"int32",
            "size":[
              6
            ]
          },
          "values":[
            0,
            4,
            8,
            12,
            16,
            20
          ]
        },
        {
          "type":"dataset",
          "name":"vertices",
          "dataset":{
            "type":"float",
            "size":[
              8,
              3
            ]
          },
          "values":[
            [
              -0.5,
              -0.5,
              0.5
            ],
            [
              0.5,
              -0.5,
              0.5
            ],
            [
              -0.5,
              0.5,
              0.5
            ],
            [
              0.5,
              0.5,
              0.5
            ],
            [
              -0.5,
              0.5,
              -0.5
            ],
            [
              0.5,
              0.5,
              -0.5
            ],
            [
              -0.5,
              -0.5,
              -0.5
            ],
            [
              0.5,
              -0.5,
              -0.5
            ]
          ],
          "attributes":[
            {
              "name":"units",
              "values":"m"
            }
          ]
        },
        {
          "type":"dataset",
          "name":"winding_order",
          "dataset":{
            "type":"int32",
            "size":[
              24
            ]
          },
          "values":[
            0,
            1,
            3,
            2,
            2,
            3,
            5,
            4,
            4,
            5,
            7,
            6,
            6,
            7,
            1,
            0,
            1,
            7,
            5,
            3,
            6,
            0,
            2,
            4
          ]
        }
      ],
      "attributes":[
        {
          "name":"NX_class",
          "values":"NXoff_geometry"
        }
      ]
    }
    """
    return json.loads(off_shape)


@pytest.fixture(scope="function")
def cylindrical_shape_json() -> dict:
    cylindrical_shape = """
    {
      "type":"group",
      "name":"pixel_shape",
      "children":[
        {
          "type":"dataset",
          "name":"cylinders",
          "dataset":{
            "type":"int32",
            "size":[
              1,
              3
            ]
          },
          "values":[
            [
              0,
              1,
              2
            ]
          ]
        },
        {
          "type":"dataset",
          "name":"vertices",
          "dataset":{
            "type":"double",
            "size":[
              3,
              3
            ]
          },
          "values":[
            [
              -0.01,
              0,
              0
            ],
            [
              -0.01,
              0.009,
              0
            ],
            [
              0.01,
              0,
              0
            ]
          ],
          "attributes":[
            {
              "name":"units",
              "values":"m"
            }
          ]
        }
      ],
      "attributes":[
        {
          "name":"NX_class",
          "values":"NXcylindrical_geometry"
        }
      ]
    }
    """
    return json.loads(cylindrical_shape)
