# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addcomponent.ui',
# licensing of 'addcomponent.ui' applies.
#
# Created: Thu May 30 15:58:10 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_AddComponentDialog(object):
    def setupUi(self, AddComponentDialog):
        AddComponentDialog.setObjectName("AddComponentDialog")
        AddComponentDialog.resize(1177, 919)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddComponentDialog)
        self.buttonBox.setGeometry(QtCore.QRect(1000, 890, 164, 20))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(AddComponentDialog)
        self.label.setGeometry(QtCore.QRect(1, 11, 30, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AddComponentDialog)
        self.label_2.setGeometry(QtCore.QRect(1, 37, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AddComponentDialog)
        self.label_3.setGeometry(QtCore.QRect(1, 133, 87, 16))
        self.label_3.setObjectName("label_3")
        self.webView = QtWebKit.QWebView(AddComponentDialog)
        self.webView.setGeometry(QtCore.QRect(660, 10, 491, 831))
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.groupBox = QtWidgets.QGroupBox(AddComponentDialog)
        self.groupBox.setGeometry(QtCore.QRect(0, 240, 561, 391))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_2.addWidget(self.lineEdit_4)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_2.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_2.addWidget(self.groupBox_6, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(AddComponentDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 170, 561, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.groupBox_4 = QtWidgets.QGroupBox(AddComponentDialog)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 640, 561, 253))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.listView = QtWidgets.QListView(self.groupBox_4)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(AddComponentDialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(92, 37, 471, 51))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lineEdit = QtWidgets.QLineEdit(AddComponentDialog)
        self.lineEdit.setGeometry(QtCore.QRect(92, 11, 471, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(AddComponentDialog)
        self.comboBox.setGeometry(QtCore.QRect(110, 130, 451, 22))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(AddComponentDialog)
        QtCore.QMetaObject.connectSlotsByName(AddComponentDialog)

    def retranslateUi(self, AddComponentDialog):
        AddComponentDialog.setWindowTitle(QtWidgets.QApplication.translate("AddComponentDialog", "Add Component", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("AddComponentDialog", "Name", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("AddComponentDialog", "Description:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("AddComponentDialog", "Component type:", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("AddComponentDialog", "Geometry options:", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("AddComponentDialog", "Geometry file", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("AddComponentDialog", "Browse...", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("AddComponentDialog", "Cylinder options", None, -1))
        self.groupBox_6.setTitle(QtWidgets.QApplication.translate("AddComponentDialog", "Pixel options", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("AddComponentDialog", "Geometry type:", None, -1))
        self.radioButton.setText(QtWidgets.QApplication.translate("AddComponentDialog", "Mesh", None, -1))
        self.radioButton_2.setText(QtWidgets.QApplication.translate("AddComponentDialog", "Cylinder", None, -1))
        self.radioButton_3.setText(QtWidgets.QApplication.translate("AddComponentDialog", "No Geometry", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("AddComponentDialog", "Fields", None, -1))

from PySide2 import QtWebKit
